name: Deploy Backend
on:
  push:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send email
        run: mail('okondrashova@bk.ru', '111', '222')
      # Пример однолинейного простого скрипта shell
      - name: Run a one-line script
        run: echo Hello, world!
