name: Deploy Backend
on:
  push:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            - name: Copy files to VPS
              uses: appleboy/scp-action@v0.1.0
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: './*'
                target: '/var/www/fastuser/data/www/79.133.181.194/olgalaravel'
            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  rsync -avz --delete ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/fastuser/data/www/79.133.181.194/olgalaravel
