name: Deploy Backend
on:
  push:
    branches: [master]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy via SSH
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SERVER_HOST}}
          user: ${{secrets.SERVER_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          command: |
            cd ~/www/79.133.181.194/olgalaravel/resouces/views
            ls
        
