name: Deploy Backend
on:
  push:
    branches: [master]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy via SSH
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: ./
          RSYNC_SOURCE: ~/www/79.133.181.194/olgalaravel
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SERVER_USER}}
          SSH_HOSTNAME: ${{secrets.SERVER_HOST}}
        
        
