name: Deploy Backend
on:
  push:
    branches: [master]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy via SSH
        uses: trendyminds/github-actions-rsync@master
        with:
          ssh_login_username: ${{ secrets.SERVER_USER }}
          remote_server_ip: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source_path: ./olgalaravel
          destination_path: ~/www/79.133.181.194/olgalaravel
        
